openapi: 3.0.3
info:
  title: Inventory Detection
  description: |-
    This project creates an inventory detection system using Amazon Rekognition and AWS serverless services.
  contact:
    email: kevintptran@gmail.com
  version: 1.0.11
externalDocs:
  description: Github Link
  url: https://github.com/ktptran/inventory-detection
tags:
  - name: Inventory
    description: Operations about overall inventory
  - name: Image
    description: Operations about images

paths:
  /inventory:
    get:
      tags:
        - Inventory
      summary: Get historical inventory
      operationId: getInventory
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /image/{keyName}:
    get:
      tags:
        - Image
      summary: Get S3 image with key name
      operationId: getImage
      parameters:
        - in: path
          name: keyName
          schema:
            type: string
          required: true
          description: UUID key value of S3 object
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /image:
    put:
      tags:
        - Image
      summary: Create image
      description: Creating a new image when closing the fridge
      operationId: putImage
      requestBody:
        description: Request for inputting image
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutImage"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"

components:
  schemas:
    PutImage:
      type: object
      properties:
        image:
          type: string
          example: base64 string
        uuid:
          type: string
          example: 0757641b-a43d-47f9-985c-585f53046c79
    ApiResponse:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
          example: 4XX
        body:
          type: string
          example: "Example response"
